### ISSUE TITLE
different APULSEPATH for 32 and 64-bit executables

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [i-rinat/apulse#19]
apulse(.template) should use different APULSEPATH on "true" multilib systems, i.e.

"/usr/lib/apulse" for skype and "/usr/lib64/apulse" for other apps

**Comment by i-rinat** [comment]
Fixed in aa73e4ecf972537649438e2076e10a40cc965bda.

Use `cmake -DAPULSEPATH=/usr/lib/apulse -DAPULSE_SEARCH_PATHS=/usr/lib/apulse:/usr/lib64/apulse ..` to configure. I never tried, though it should work.

**Comment by ryanpcmcquen** [comment]
@MiRacLe-RPZ can you test this and verify it works? If so, I will push it to SBo.

**Comment by MiRacLe-RPZ** [comment]
I don't have any 64-bit sound-applications that requires PA, but i confirm - "trick" with multiple LD_PRELOAD_PATH works:

$ apulse skype
$ apulse paprefs
$ lsof |grep apulse
skype      4737    miracle  mem       REG                8,8    86804   705529 /usr/lib/apulse/libpulse.so.0
paprefs   10934    miracle  mem       REG                8,8    85856   705293 /usr/lib64/apulse/libpulse.so.0

Thanks.
