### ISSUE TITLE
Add compatibility for Musl C

### ISSUE THREAD

**Issue by itoffshore** [i-rinat/apulse#20]
--- apulse-0.1.5/src/apulse-threaded-mainloop.c
    +++ apulse-0.1.5/src/apulse-threaded-mainloop.c.new
    @@ -105,7 +105,7 @@
         m->m = pa_mainloop_new();
 
         pthread_mutexattr_init(&mutex_attr);
    -    pthread_mutexattr_settype(&mutex_attr, PTHREAD_MUTEX_RECURSIVE_NP);
    +    pthread_mutexattr_settype(&mutex_attr, PTHREAD_MUTEX_RECURSIVE);
         pthread_mutex_init(&m->lock, &mutex_attr);
         pthread_mutexattr_destroy(&mutex_attr);

This patch is required for building in Musl C.

**Comment by i-rinat** [comment]
Fixed in b4429611bc828f9eaaa382ffcad2048945e72a0d.
