### ISSUE TITLE
Skype doesn't see my mic

### ISSUE THREAD

**Issue by Ilya87** [i-rinat/apulse#23]
I can hear sound from skype, skype can't hear me.
arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC892 Analog [ALC892 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 2: ALC892 Alt Analog [ALC892 Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

audacity records mic from front mic
https://yadi.sk/i/TZ-kYrI3eDzZB - debug output

**Comment by i-rinat** [comment]
Open Edit->Preferences in Audacity. Select "Devices" pane. Which device for recording is selected there? Does recording work when you choose "default" device?

**Comment by Ilya87** [comment]
HDA Intel PCH:ALC 892 Analog (hw:0,0):Front Mic:1

**Comment by i-rinat** [comment]
Try to launch apulse that way:
```APULSE_CAPTURE_DEVICE=plughw:0,0 apulse skype```
or, if that doesn't work,
```APULSE_CAPTURE_DEVICE=hw:0,0 apulse skype```

**Comment by Ilya87** [comment]
APULSE_CAPTURE_DEVICE=plughw:0,0 apulse skype works. Thank you! I should better read README.md
