### ISSUE TITLE
Skype виснет когда работает Amarok

### ISSUE THREAD

**Issue by Feduch** [i-rinat/apulse#28]
Приветствую i-rinat!

Настраивал apulse как описано тут http://habrahabr.ru/post/241045/

arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC269VC Analog [ALC269VC Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

pcm.!default {
         type asym
         playback.pcm {
                 type plug
                 slave.pcm "hw:0,0"
         }
         capture.pcm {
                 type plug
                 slave.pcm "hw:0,0"
         }
 }

Если работает Amarok, то вываливается эти сообщения.

[apulse] [error] do_connect_pcm, snd_pcm_open, Устройство или ресурс занято
[apulse] [error] do_connect_pcm, snd_pcm_open, Устройство или ресурс занято

**Comment by i-rinat** [comment]
А Amarok через какое устройство проигрывает?

**Comment by Feduch** [comment]
Удалил файл с настройками

pcm.!default {
type asym
playback.pcm {
type plug
slave.pcm "hw:0,0"
}
capture.pcm {
type plug
slave.pcm "hw:0,0"
}
}

теперь не зависает)

Спасибо за apulse!

**Comment by i-rinat** [comment]
Я хотел сказать, что если Amarok настроен на воспроизведение через `hw:0,0`, то он монопольно захватит устройство, и открыть его будет уже нельзя. В apulse ожидается, что все потоки текут через dmix/dsnoop, благодаря чему множество клиентов могут использовать одно устройство одновременно.

**Comment by Feduch** [comment]
Спасибо, внесли ясность!
