### ISSUE TITLE
Не устанавливается через checkinstall -D в Debian

### ISSUE THREAD

**Issue by xintrea** [i-rinat/apulse#30]
Не проходит checkinstall -D в Debian. Директория build. Пишет следующее:

Installing with make install...
========================= Результаты установки ===========================
make[2]: *** Нет правила для сборки цели «../src/trace.c», требуемой для «CMakeFiles/trace-helper.dir/src/trace.c.o».  Останов.
CMakeFiles/Makefile2:165: ошибка выполнения рецепта для цели «CMakeFiles/trace-helper.dir/all»
make[1]: *** [CMakeFiles/trace-helper.dir/all] Ошибка 2
Makefile:117: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2
****  Установка неудачна. Отменяется создание пакета.
Очищается...OK
Удачи.

В то же время make install в директории build проходит нормально:

[  6%] Building C object CMakeFiles/trace-helper.dir/src/trace.c.o
Linking C static library libtrace-helper.a
[  6%] Built target trace-helper
Linking C shared library libpulse.so
[ 87%] Built target pulse
Linking C shared library libpulse-simple.so
[ 93%] Built target pulse-simple
Linking C shared library libpulsecommon-5.0.so
[100%] Built target pulsecommon-5.0
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/bin/apulse
-- Installing: /usr/lib/apulse/libpulse-simple.so.0
-- Installing: /usr/lib/apulse/libpulse-simple.so
-- Installing: /usr/lib/apulse/libpulsecommon-5.0.so
-- Installing: /usr/lib/apulse/libpulse.so.0
-- Installing: /usr/lib/apulse/libpulse.so

**Comment by i-rinat** [comment]
Стоит попробовать перед `checkinstall` явно вызвать `make`.

**Comment by xintrea** [comment]
В том то и дело что make  перед checkinstall, естественно, запускаю.
31 мая 2015 г. 12:52 пользователь "Rinat Ibragimov" <
notifications@github.com> написал:

**Comment by i-rinat** [comment]
По сообщениям выходит, что make не нашёл файла `../src/trace.c`, посчитал его одной из целей, но не нашёл правила для сборки. Возможно, при запуске checkinstall меняет директорию, поэтому по пути `../src/trace.c` ничего нет?

**Comment by i-rinat** [comment]
Since both compilation via `make` and installing via `make install` work, this is not a bug. I tried to build package with checkinstall successfully (and I actually use it to create Debian package myself). So there are no obvious incompatibilities with checkinstall either.

There is nothing I can do in `apulse` to resolve the issue. And there is no enough information to debug the issue.
