### ISSUE TITLE
Cannot link 32 bit version

### ISSUE THREAD

**Issue by WildLynxDev** [i-rinat/apulse#39]
I'm trying to compile 32 bit version to run skype without active pulseaudio.
I'm not familiar with cmake, so I cannot find what is wrong.
Looks like linker cannot find 32bit libraries, but they are present, and ldconfig -p shows them too.

Here is the output:

[root@OrcogreCastle apulse-0.1.7]# mkdir build
[root@OrcogreCastle apulse-0.1.7]# cd build/
[root@OrcogreCastle build]# CFLAGS=-m32 cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release  ..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/share/colorgcc/cc
-- Check for working C compiler: /usr/share/colorgcc/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/share/colorgcc/c++
-- Check for working CXX compiler: /usr/share/colorgcc/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for modules 'glib-2.0;alsa'
--   found glib-2.0, version 2.42.1
--   found alsa, version 1.0.28
-- Configuring done
-- Generating done
-- Build files have been written to: /root/work/apulse/apulse-0.1.7/build
[root@OrcogreCastle build]# make
Scanning dependencies of target trace-helper
[  6%] Building C object CMakeFiles/trace-helper.dir/src/trace.c.o
Linking C static library libtrace-helper.a
[  6%] Built target trace-helper
Scanning dependencies of target pulse
[ 12%] Building C object CMakeFiles/pulse.dir/src/apulse-channel-map.c.o
[ 18%] Building C object CMakeFiles/pulse.dir/src/apulse-context.c.o
[ 25%] Building C object CMakeFiles/pulse.dir/src/apulse-format-info.c.o
[ 31%] Building C object CMakeFiles/pulse.dir/src/apulse-mainloop.c.o
[ 37%] Building C object CMakeFiles/pulse.dir/src/apulse-misc.c.o
[ 43%] Building C object CMakeFiles/pulse.dir/src/apulse-operation.c.o
[ 50%] Building C object CMakeFiles/pulse.dir/src/apulse-proplist.c.o
[ 56%] Building C object CMakeFiles/pulse.dir/src/apulse-signal.c.o
[ 62%] Building C object CMakeFiles/pulse.dir/src/apulse-stream.c.o
[ 68%] Building C object CMakeFiles/pulse.dir/src/apulse-threaded-mainloop.c.o
[ 75%] Building C object CMakeFiles/pulse.dir/src/util.c.o
[ 81%] Building C object CMakeFiles/pulse.dir/src/ringbuffer.c.o
[ 87%] Building C object CMakeFiles/pulse.dir/src/notimplemented.c.o
Linking C shared library libpulse.so
/usr/bin/ld: skipping incompatible /usr/lib64/libglib-2.0.so when searching for -lglib-2.0
/usr/bin/ld: cannot find -lglib-2.0
/usr/bin/ld: skipping incompatible /usr/lib64/libasound.so when searching for -lasound
/usr/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status
CMakeFiles/pulse.dir/build.make:386: recipe for target 'libpulse.so.0' failed
make[2]: *** [libpulse.so.0] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/pulse.dir/all' failed
make[1]: *** [CMakeFiles/pulse.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
[root@OrcogreCastle build]# ll /usr/lib/libgl
libglapi.so.0            libglapi.so.0.0.0        libglib-2.0.so.0         libglib-2.0.so.0.4200.1  
[root@OrcogreCastle build]# ll /usr/lib/libgli
libglib-2.0.so.0         libglib-2.0.so.0.4200.1  
[root@OrcogreCastle build]# ll /usr/lib/libglib-2.0.so.0
lrwxrwxrwx 1 root root 23 Aug  2  2015 /usr/lib/libglib-2.0.so.0 -> libglib-2.0.so.0.4200.1*
[root@OrcogreCastle build]# ll /usr/lib/libasou
libasound.so.2      libasound.so.2.0.0  
[root@OrcogreCastle build]# ll /usr/lib/libasound.so.2
lrwxrwxrwx 1 root root 18 Jun 18  2014 /usr/lib/libasound.so.2 -> libasound.so.2.0.0*
[root@OrcogreCastle build]# uname -a
Linux OrcogreCastle 4.4.13-desktop-1.mga5 #1 SMP Fri Jun 10 12:16:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by i-rinat** [comment]
To create 32-bit library you need 32-bit versions `libasound.so` and `libglib-2.0.so`. And if you have recent enough glib2, you need its headers too. I don't remember when, but now `glibconfig.h` header, which is implicitly included when one uses `glib.h`, is architecture-dependent.

So far the easiest way is to build in 32-bit chroot.

**Comment by h1z1** [comment]
Ran into this, spent hours trying to get pkg-config to do what I wanted.  Gave up.  cmake with -m32 will try to build but uses 64bit pkg-config. 

SOURCE_DIR=~/git/apulse
       DP="${PFX:-}/usr"

        ## cflags - 32bit and 64bit systems have 32bit in /usr/lib, 64bit in /usr/lib64
        ##          if we aren't installing in system directories, use lib32 and lib64
        ##          else leave as lib an lib64

        CF="-DAPULSEPATH=${DP}/lib"
        CMAKE_INSTALL_PREFIX32=$DP/lib
        CMAKE_INSTALL_PREFIX64=$DP/lib64

build_32() {
	cd $SOURCE_DIR
	[ ! -d build32 ] && { mkdir build32; } 
	cd build32
	## ${CF}32 if not using system install
	CFLAGS="-m32 ${CF}"
	cmake -DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL32 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32 ..
	make
}

**Comment by i-rinat** [comment]
> cmake with -m32 will try to build but uses 64bit pkg-config. 

`PKG_CONFIG_PATH` can be used to tell pkg-config where to look for `.pc` files:

```
PKG_CONFIG=/usr/lib/pkgconfig CFLAGS=-m32 cmake -DCMAKE_BUILD_TYPE=Release ..
```
