### ISSUE TITLE
libpulse-mainloop-glib.so

### ISSUE THREAD

**Issue by cxd4** [i-rinat/apulse#60]
I'm very happy that uninstalling PulseAudio from Slackware has been made so easy.

The only drawback is that a few KDE applications don't seem to run anymore.  Maybe this wrapper is missing some exports somewhere?

I have to use Xfce for now.  When I run `startx` on Slackware, KDE initialization crashes with:
```
Could not open library ksmserver: Cannot load library /usr/lib/libkdeinit4_ksmserver.so: (libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory)
ksmserver: error while loading shared libraries: libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory
startkde: Shutting down...
```

I followed these instructions to remove PulseAudio from Slackware 14.2:
https://docs.slackware.com/howtos:multimedia:pulseaudio_non-default
_Removing PulseAudio Completely_

**Comment by cxd4** [comment]
Looks like the majority of KDE applications still run within Xfce.

Dolphin file manager is one of the ones that does not.  This `libpulse-mainloop-glib` library seems to be a dependency of that and a few others, but maybe this is only on the Slackware distribution?  Or I would not have been the first person to write this issue.

**Comment by i-rinat** [comment]
I've added stub for `libpulse-mainloop-glib.so` in c2f251f59fef6bf1dc30826e9c7428943fdb805f. Functions there do nothing. But it looks like Dolphin doesn't use them. They are kind of needed for Phonon, I think. So, unless something in Dolphin tries to produce a sound, just having a library with three functions should be enough.

**Comment by cxd4** [comment]
Awesome!

**Comment by Techwolf** [comment]
I just got hit with this bug. Thank you for fixing.

`./qDslrDashboard: error while loading shared libraries: libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory`
