### ISSUE TITLE
apulse-0.1.10 can't handle ALSA softvol type

### ISSUE THREAD

**Issue by aerique** [i-rinat/apulse#61]
Hi,

First of all, thanks for writing apulse!  I never really like PulseAudio while I could get away with a really simple ALSA dmix config and I was kinda miffed to discover Firefox stopped working after kicking off PulseAudio from my new favorite distribution (Void Linux).

I'm using the `~/.asoundrc` that I've pasted at the end of this message.  It works for my purposes: audio gets send to both my headphones and HDMI which are two separate cards:

    $ aplay -l
    **** List of PLAYBACK Hardware Devices ****
    card 0: PCH [HDA Intel PCH], device 0: ALC1220 Analog [ALC1220 Analog]
      Subdevices: 0/1
      Subdevice #0: subdevice #0
    …
    card 1: NVidia [HDA NVidia], device 3: HDMI 0 [HDMI 0]
      Subdevices: 0/1
      Subdevice #0: subdevice #0
    …

And I can easily mute one of them or both.  By using the softvol plugin I'm able to easily control the volume of both (I couldn't control volume of HDMI at all otherwise, alsamixer also didn't show anything):

    $ amixer -c 1
    Simple mixer control 'IEC958',0
      Capabilities: pswitch pswitch-joined
      Playback channels: Mono
      Mono: Playback [on]
    Simple mixer control 'IEC958',1
    …

However starting Firefox with just `apulse firefox` didn't work for me, I got the following message:

    $ apulse firefox --ProfileManager --new-instance
    [apulse] [error] do_connect_pcm: can't set sample format 14 ("FLOAT_LE") for playback device "default". Error code -22 (Invalid argument)
    [apulse] [error] do_connect_pcm: failed to open ALSA device. Apulse does no resampling or format conversion, leaving that task to ALSA plugins. Ensure that selected device is capable of playing a particular sample format at a particular rate. They have to be supported by either hardware directly, or by "plug" and "dmix" ALSA plugins which will perform required conversions on CPU.

I had to start it as follows for it to work: `APULSE_PLAYBACK_DEVICE=pimo apulse firefox`

My asoundrc:

    # ~/.asoundrc
    
    pcm.internal {
        type dmix
        ipc_key 1024
        slave {
            pcm "hw:0,0"
            period_size 2048
            period_time 0
        }
    }
    
    pcm.display {
        type dmix
        ipc_key 2048
        slave {
            pcm "hw:1,3"
            period_size 2048
            period_time 0
        }
    }
    
    pcm.both {
        type route
        slave.pcm {
            type multi
            slaves.a.pcm "internal"
            slaves.b.pcm "display"
            slaves.a.channels 2
            slaves.b.channels 2
            bindings.0.slave a
            bindings.0.channel 0
            bindings.1.slave a
            bindings.1.channel 1
            bindings.2.slave b
            bindings.2.channel 0
            bindings.3.slave b
            bindings.3.channel 1
        }
        ttable.0.0 1
        ttable.1.1 1
        ttable.0.2 1
        ttable.1.3 1
    }
    
    pcm.pimo {
        type plug
        slave.pcm "both"
    }
    
    pcm.!default {
        type softvol
        slave.pcm "pimo"
        control.name "PCM"
        control.card 0
    }
    
    ctl.!default {
        type hw
        card 0
    }

**Comment by Alexander--** [comment]
@aerique Seems like softvol does not advertise support for required formats. have you tried to swap it with plug (e.g. place plug *before* softvol)? If that does not work… Perhaps using plug twice (before and after softvol) might be able to resolve the problem.

Or someone could fix softvol.

**Comment by aerique** [comment]
Ah yes thanks, swapping softvol and plug works!  Now, why didn't I think of that myself?

That fixes the issue for me.
