### ISSUE TITLE
gqrx crashes with PULSE_0 not defined in libpulse-simple.so

### ISSUE THREAD

**Issue by Malvineous** [i-rinat/apulse#62]
I am trying to use the [gqrx](https://github.com/csete/gqrx) program with apulse however it seems not to like things.  Am I doing something wrong?
```
$ apulse gqrx
...
1500776179.239 [apulse  4101] Z pa_simple_new server=(null), name=GQRX, dir=1, dev=(null), stream_name=Audio output, ss=0x29d2f48, map=(nil), attr=(nil)
../src/pulseaudio/pa_sink.cc: pa_simple_new() failed: Oops.
...
gqrx: relocation error: gqrx: symbol pa_simple_write, version PULSE_0 not defined in file libpulse-simple.so.0 with link time reference
```
It seems to be picking up the right libraries:
```
$ apulse ldd /usr/bin/gqrx
        libpulse-simple.so.0 => /usr/lib/apulse/libpulse-simple.so.0 (0x00007f2527c35000)
        libpulse.so.0 => /usr/lib/apulse/libpulse.so.0 (0x00007f2527a1c000)
```
So I'm not sure whether I am doing something wrong.  Any hints?

**Comment by i-rinat** [comment]
Hi. Looks like I've added implementation of `pa_simple_write` after v0.1.10, so code from `master` branch may work.

**Comment by Malvineous** [comment]
Ah, my apologies!  I didn't realise it was already fixed!  I just tested the `master` branch and everything works well with that.  Thank you for the quick response!
