### ISSUE TITLE
How to uninstall/remove apulse?

### ISSUE THREAD

**Issue by albocc** [i-rinat/apulse#72]
I installed apulse manually by running `make install`. Now that I found apulse in my distro's repos, I want to remove apulse and reinstall it from my distro's repo.

How can I undo what `make install` did? Maybe adding this info to the readme would be great, too.

**Comment by i-rinat** [comment]
I don't think there is an automatic uninstall procedure. At least, CMake doesn't generate target `uninstall`. Instead, it creates file `install_manifest.txt` in a build directory. It contains the list of files installed to the system. Try to delete files listed there.

I also suggest using of `checkinstall` or some similar software for installation from sources. `Checkinstall` creates a package, so it's easier to track installed files. For example, uninstall them easily.

**Comment by albocc** [comment]
Thanks for the hint!

What I did now solved the issue. Maybe you can note the following command in the README as a workaround to uninstall apulse:

    # cat build/install_manifest.txt | xargs rm

**Comment by i-rinat** [comment]
I personally don't like any commands with `rm`, especially those containing iterations over lists. One should definitely know what they delete. Copying such commands from the web is dangerous.

**Comment by albocc** [comment]
It sure is a better idea to first run only `cat` to see what will be deleted. 

If you want you can check out this post that shows a little workaround to add an uninstall target to CMake: https://www.linux.com/blog/cmake-recipe-5-adding-uninstall-target-your-project

**Comment by i-rinat** [comment]
I honestly do not understand why `uninstall` target is needed. It's quite useless even in autotools, as works as intended only if you have the same configuration, same prefix, and so on. There is absolutely no guarantee that uninstallation procedure will work.

**Comment by albocc** [comment]
Well you saw one example now ;-)

**Comment by i-rinat** [comment]
Are you going to uninstall a lot?

**Comment by albocc** [comment]
Not necessarily but someone else might need to do what I had to do, too. 
It just makes sense to me to have an "uninstall" when there is a "install".
