### ISSUE TITLE
A fix for common module problems

### ISSUE THREAD

**Issue by ikolinahr** [i-rinat/apulse#73]
I spent way too much time trying to get cmake to work because of the following error:

> -- checking for modules 'glib-2.0;alsa'
> --   package 'glib-2.0' not found
> --   package 'alsa' not found

The solution for me was:

> sudo apt-get install libglib2.0-dev
> sudo apt-get install libasound2-dev

The first module, 'glib-2.0', was obvious. The second one, 'alsa', was not easy to figure out. It needed 'libasound2-dev', but was asking for 'alsa'

**Comment by i-rinat** [comment]
Modules here are pkg-config modules. What pkg-config actually needs is `.pc` files. They are usually come with `-dev` packages.

You can search for them using `apt-file` utility. Something like this:
```
$ apt-file search /glib-2.0.pc
libglib2.0-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc
$ apt-file search /alsa.pc
libasound2-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/alsa.pc
$ 
```

**Comment by ikolinahr** [comment]
Thank you for that.That is very good to know. As a Linux user (not a developer or sysadmin) just wanting to get sound from Firefox once again, how can I be expected to suss out this information on my own. Could I kindly ask that this be added to the README file for the next person in my position. Thank you again.

**Comment by i-rinat** [comment]
Now, since 5a1c3987ec2c8c8f7ede0d80f4eda6d8fd92ebf0, required packages are mentioned in README file.
