### ISSUE TITLE
How can I create a systewide environment as defined in the wrapper script?

### ISSUE THREAD

**Issue by woweil** [i-rinat/apulse#74]
Hi all,

does someone have an idea how I can set the defined environment in wrapper script systemwide?

I have tried this with the .xsession in this way:

#!/bin/sh

APULSEPATH="/usr/lib64/apulse:/usr/lib/apulse"
export APULSEPATH

LD_LIBRARY_PATH=$APULSEPATH${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH} exec "$@^
export LD_LIBRARY_PATH

But that does not work. I do not see the defined values with the command env; also firefox tells me to use pulseaudio. If I invoke firefox with apulse then the sound works.

Many thanks for tips.

Greetings
Wolfram

**Comment by i-rinat** [comment]
I would strongly suggest to avoid enabling apulse system-wide, as it's far from a complete implementation of PulseAudio API. But if you want to do that anyway, it's easier to just copy (or move) libraries from `/usr/lib64/apulse` and `/usr/lib/apulse` to `/usr/lib64` and `/usr/lib` correspondingly.

Using of `LD_LIBRARY_PATH` variable is a way to say dynamic linker where to look for the libraries requested by application. If you set `LD_LIBRARY_PATH` system-wide, its the same as adding another directory to `/etc/ld.so.conf`.

**Comment by woweil** [comment]
Many thanks.

Your suggestion works. I even could deinstall the regarding libs of the distribution (Fedora). After that I have excluded them from being installed.

At least Firefox 57works like a charme.


Greetings
Wolfram
