### ISSUE TITLE
wrong default device

### ISSUE THREAD

**Issue by diggit** [i-rinat/apulse#76]
Hi, I am unable to route audio to my default ALSA device. (Sound goes from hw:0,0 with mixing. If I set `APULSE_PLAYBACK_DEVICE` to plughw:0,0 , sound goes from that device but, no mixing happens.)

Here is my `.asoundrc`
```
pcm.!surround51 {
        type vdownmix
        slave.pcm "default"
}
pcm.!splitter {
        type route;
        slave.pcm {
                type multi;
                slaves.a.pcm "analog_dmixer";
                slaves.b.pcm "spdif_dmixer";
                slaves.a.channels 2;
                slaves.b.channels 2;
                bindings.0.slave a;
                bindings.0.channel 0;
                bindings.1.slave a;
                bindings.1.channel 1;
                bindings.2.slave b;
                bindings.2.channel 0;
                bindings.3.slave b;
                bindings.3.channel 1;
        }
        ttable {
                0.0 = 1;
                1.1 = 1;
                0.2 = 1;
                1.3 = 1;
        }
}
pcm.analog_dmixer  {
        type dmix
        ipc_key 1024
        slave {
                pcm "hw:0,0"
                #rate 48000
                channels 2
                #periods 128
                period_time 0
                period_size 1024
                buffer_size 4096
        }
        bindings {
                0 0
                1 1
        }
}
pcm.spdif_dmixer  {
        type dmix
        ipc_key 1025
        slave {
                pcm "hw:0,8"
                #rate 48000
                channels 2
                #periods 128
                period_time 0
                period_size 1024
                buffer_size 4096
        }
        bindings {
                0 0
                1 1
        }
}
#using splitter
pcm.!default {
        type plug
        slave.pcm "splitter"
}
defaults.pcm.rate_converter "speexrate_medium"
```

This setup takes input and splits it for my speakers on laptop (0,0) and for display port monitor (0,8). Separate dmix instances for each device. Maybe there is some problem, but other software using alsa backend works well.

What should I do to convince apulse to use my default device?

I'm testing apulse with firefox 58.0b15 (64-bit) on Arch Linux.

**Comment by i-rinat** [comment]
I'm not proficient with ALSA configuration, as I always used a default one.

From what I see from the configuration file, there are four channels? Perhaps, that's the reason? `apulse` does no negotiation on sample format, frequency and channel count. It just tries to open a device with the same exact parameters that application asked, to avoid any resampling. In a default configuration some magic happens, and it works. In custom configurations anything can go wrong, unless it somehow implements the same magic.

**Comment by diggit** [comment]
There are only 2 channels. My `splitter` just creates 4 bindings and routes channels 0 a 1 to them.

I did another experiment. I changed default's `slave.pcm` to send audio directly to `spdif_splitter`, applied changes and every app using ALSA had audio output on SPDIF (hw:0,8) only. Apulse behavior did not change at all. It looks like, (only) apulse completely ignores my `~/.asoundrc`. I'am not sure, how this is possible...

**Comment by i-rinat** [comment]
> It looks like, (only) apulse completely ignores my ~/.asoundrc. I'am not sure, how this is possible...

It would be surprising.
But no, there are no tricks in apulse, as far as I know. It opens device named "default", or uses name from `APULSE_PLAYBACK_DEVICE` environment variable, if it's set. Capture is implemented the same way, but variable `APULSE_CAPTURE_DEVICE` is used instead.

**Comment by poluyan** [comment]
Same problem here. Arch Linux, Firefox 58 and simple config. The problem is in Firefox, downgrading to 57 fixing the issue. Other applications works fine with apulse.
`.asoundrc` 
```
pcm.!default
{
    type hw
    card 0
}
ctl.!default
{
    type hw
    card 0
}
pcm.!default
{
    type plug
    slave.pcm "dmix"
}
```
apulse firefox
```
Sandbox: seccomp sandbox violation: pid 8082, tid 9119, syscall 16, args 42 2147767296 140489722709304 0 0 0.
Sandbox: seccomp sandbox violation: pid 8082, tid 9119, syscall 16, args 42 2147767296 140489722709320 0 0 0.
ALSA lib pcm_direct.c:1421:(snd1_pcm_direct_initialize_poll_fd) unable to open timer 'hw:CLASS=3,SCLASS=0,CARD=0,DEV=0,SUBDEV=0'
ALSA lib pcm_dmix.c:1183:(snd_pcm_dmix_open) unable to initialize poll_fd
[apulse] [error] do_connect_pcm: can't open playback device "default". Error code -38 (Функция не реализована)
[apulse] [error] do_connect_pcm: can't open playback device "default". Error code -38 (Функция не реализована)
[apulse] [error] do_connect_pcm: failed to open ALSA device. Apulse does no resampling or format conversion, leaving that task to ALSA plugins. Ensure that selected device is capable of playing a particular sample format at a particular rate. They have to be supported by either hardware directly, or by "plug" and "dmix" ALSA plugins which will perform required conversions on CPU.
[apulse] [error] do_connect_pcm: failed to open ALSA device. Apulse does no resampling or format conversion, leaving that task to ALSA plugins. Ensure that selected device is capable of playing a particular sample format at a particular rate. They have to be supported by either hardware directly, or by "plug" and "dmix" ALSA plugins which will perform required conversions on CPU.
```

**Comment by i-rinat** [comment]
> seccomp sandbox violation: pid 8082, tid 9119, syscall 16, args 42 2147767296 140489722709304 0 0 0.

Firefox gradually tightens its sandboxing. System call 16 (it's `ioctl()` on x86-64) is now forbidden too by default. It's not used with PulseAudio, since a separate process talks to the hardware, but with apulse you need to enable that system call, since `apulse` libraries work in the same process.

Add `16` to `security.sandbox.content.syscall_whitelist` on `about:config` page.

**Comment by poluyan** [comment]
> Add 16 to security.sandbox.content.syscall_whitelist on about:config page.

This is the solution for my issue. The problem with sandbox again. Thank you very much for your help!
I hope it will work for others as well.

**Comment by diggit** [comment]
@poluyan this is not same issue. Solution to yours was already described in readme ;)

**Comment by poluyan** [comment]
Oh, yes, I'm sorry. I've missed the point. I thought it's the same cos "wrong default device" and "Firefox 58".  I even didn't know about the "Known issues" section in readme. Thanks.

**Comment by nuskorpios** [comment]
I had this problem too. But, according to [this article][codelab], `apulse(1)` is "ignoring" your `.asoundrc` file because you didn't set `security.sandbox.content.read_path_whitelist` (note it's "**read**\_path\_whitelist", not "write\_path\_whitelist") to point to it. Remember that

> [...] Firefox now have a sandbox, that blocks file access.

I tested it on Void Linux with musl libc and Firefox 58 and Just Works(TM).

[codelab]: https://codelab.wordpress.com/2017/12/11/firefox-drops-alsa-apulse-to-the-rescue/

**Comment by diggit** [comment]
@nuskorpios Thanks!

@i-rinat can you add info about necessity to add .asoundrc (if not empty) to sandbox read whiletlist to README?
