### ISSUE TITLE
apulse can't find AppImage in $PATH.

### ISSUE THREAD

**Issue by globetrotterdk** [i-rinat/apulse#80]
Firstly, thank you very much for apulse. I am experiencing a problem trying to use apulse with an AppImage program in $PATH. MuseScore-2.1-x86_64.AppImage resides in ~/bin, which is in $PATH:
`$ echo $PATH
/home/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`

However, when I run apulse ./MuseScore-2.1-x86_64.AppImage, I get:
`$ apulse ./MuseScore-2.1-x86_64.AppImage
/usr/bin/apulse: 5: exec: ./MuseScore-2.1-x86_64.AppImage: not found`

I am trying to run this on a fresh, minimal, vanilla Devuan Jessie install with i3wm as the window manager. It of course is using Alsa and apulse.

Optimally, the idea is to run the above command through an entry in the i3 config file, such as:
`bindsym $mod+n exec apulse ./MuseScore-2.1-x86_64.AppImage`

I know that the system recognizes MuseScore in $PATH as it appears in dmenu.

**Comment by probonopd** [comment]
Just a guess, what happens if you copy or symlink `MuseScore-2.1-x86_64.AppImage` to `/usr/local/bin/musescore`?

**Comment by globetrotterdk** [comment]
Thanks probonopd. Nice to hear from you again. That solved the issue. Please explain the reason for this. Is this an AppImage thing or an apulse thing?

**Comment by probonopd** [comment]
This is an `apulse` thing. Looks like it searches for `musecore` on the `$PATH`.

**Comment by i-rinat** [comment]
> `$ apulse ./MuseScore-2.1-x86_64.AppImage`

What you are trying to do here is to run `MuseScore-2.1-x86_64.AppImage` binary from **current directory**. That's what `./` at the beginning do. Shell doesn't try paths in `PATH`, since you are pointing to the exact location. For example, when you try to run `ls`, shell searches for `ls`, and eventually invokes `/bin/ls`. But when you run `./ls`, it fails to run `/bin/ls`, unless you are currently in `/bin`.

Try:
```
$ apulse MuseScore-2.1-x86_64.AppImage
```

**Comment by globetrotterdk** [comment]
Ahh. Confusion averted. Thanks.
`$ apulse MuseScore-2.1-x86_64.AppImage`
works fine :)
