### ISSUE TITLE
Problems with certain games.

### ISSUE THREAD

**Issue by Catoptrix** [i-rinat/apulse#92]
Hi,

First of all, thank you for this. Finally Discord works now. 
I have an usb card and alsa 80% of times detects it. Sometimes on startup it chooses the motherboard soundcard as default. No idea why that happens sometimes.

Unfortunately still have some problems with certain games like "Pyre", which still has no sound:
```
Number of audio devices: 24
Driver #0: default:CARD=PCH, Speaker Mode: STEREO
Driver #1: default:CARD=CODEC, Speaker Mode: STEREO
Driver #2: sysdefault:CARD=CODEC, Speaker Mode: STEREO
Driver #3: front:CARD=CODEC,DEV=0, Speaker Mode: STEREO
Driver #4: surround21:CARD=CODEC,DEV=0, Speaker Mode: STEREO
Driver #5: surround40:CARD=CODEC,DEV=0, Speaker Mode: QUAD
Driver #6: surround41:CARD=CODEC,DEV=0, Speaker Mode: STEREO
Driver #7: surround50:CARD=CODEC,DEV=0, Speaker Mode: SURROUND
Driver #8: surround51:CARD=CODEC,DEV=0, Speaker Mode: _5POINT1
Driver #9: surround71:CARD=CODEC,DEV=0, Speaker Mode: _7POINT1
Driver #10: iec958:CARD=CODEC,DEV=0, Speaker Mode: STEREO
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Driver #11: pulse, Speaker Mode: STEREO
Driver #12: sysdefault:CARD=PCH, Speaker Mode: STEREO
Driver #13: front:CARD=PCH,DEV=0, Speaker Mode: STEREO
Driver #14: surround21:CARD=PCH,DEV=0, Speaker Mode: STEREO
Driver #15: surround40:CARD=PCH,DEV=0, Speaker Mode: QUAD
Driver #16: surround41:CARD=PCH,DEV=0, Speaker Mode: STEREO
Driver #17: surround50:CARD=PCH,DEV=0, Speaker Mode: SURROUND
Driver #18: surround51:CARD=PCH,DEV=0, Speaker Mode: _5POINT1
Driver #19: surround71:CARD=PCH,DEV=0, Speaker Mode: _7POINT1
Driver #20: hdmi:CARD=NVidia,DEV=0, Speaker Mode: STEREO
Driver #21: hdmi:CARD=NVidia,DEV=1, Speaker Mode: STEREO
Driver #22: hdmi:CARD=NVidia,DEV=2, Speaker Mode: STEREO
Driver #23: hdmi:CARD=NVidia,DEV=3, Speaker Mode: STEREO
Using driver #0
```

Driver 0 should be the usb default soundcard, isn't it? Since I installed apulse nothing changed in regard of other games which had sound, they still have sound. Like wine with Path of Exile works fine, Halcyon6 or caves of qud. 

Not sure if it is apulse related, any ideas? :)

**Comment by Catoptrix** [comment]
Ok Drive 0 is not my default soundcard defined by .asoundrc
it should be driver 1. Where can I define that? How do I change this default?

**Comment by i-rinat** [comment]
I can't say whenever it's related to apulse or not. My first guess would be "yes", since there are a ton of API not implemented in apulse. By the way, if you build from source, and use `-DWITH_TRACE=1` option for CMake, apulse will spam to the standard output (usually goes to the terminal you're starting programs from) list of unimplemeted calls. Some calls are not crucial, but some are actually important. And their absence could be a reason for non-working sound. By default, apulse is built without tracing.

As for the multiple card issues, I can only give link to the ALSA wiki: https://alsa.opensrc.org/MultipleCards. I'm by no means an ALSA expert. Sorry.

**Comment by i-rinat** [comment]
I don't think it's the game that chooses which driver to choose. It's likely that order of cards is chosen at startup time. Which module initializes hardware faster, becomes first. And after that apulse just uses `default` which corresponds to the first card in the list.

**Comment by mviereck** [comment]
You probably can fix this with setting environment variable `ALSA_CARD`. Check card names in output of `aplay -l`. 
In my case, I have to set `export ALSA_CARD=Generic`. Otherwise ALSA tries to access my non-connected HDMI port.

**Comment by Catoptrix** [comment]
Hey thanks for this information. I will try it out.
Also if somebody else comes around, I will post this link: https://ptspts.blogspot.com/2009/03/how-to-select-alsa-sound-card-and-have.html

Thx all, I will close this now. Peace
